# -*- coding: utf-8 -*-
"""Quiz App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGy5wF4H4D_rP2zk-_vvwNO0fVRGk8Sx
"""

# KBC style quiz game in Python

# 1️⃣ Questions and answers (list of tuples)
questions = [
    ("Who is the creator of Python?", "b"),
    ("What is the capital of India?", "a"),
    ("What is 2 + 2?", "c"),
]

options = [
    ["a) Elon Musk", "b) Guido van Rossum", "c) James Gosling", "d) Dennis Ritchie"],
    ["a) New Delhi", "b) Mumbai", "c) Kolkata", "d) Chennai"],
    ["a) 5", "b) 22", "c) 4", "d) 6"],
]

prizes = [1000, 5000, 10000]  # prize money for each correct answer

total_amount = 0

print("WELCOME TO KBC!\n")

# 2️⃣ Loop through questions
for i in range(len(questions)):
    q, correct_ans = questions[i]

    print(f"Question {i+1}: {q}")
    for opt in options[i]:
        print(opt)

    user_ans = input("Enter your answer (a/b/c/d): ").lower()

    if user_ans == correct_ans:
        total_amount += prizes[i]
        print(f"Correct! You won ₹{prizes[i]}\n")
    else:
        print("Wrong answer! Game Over.")
        break

# 3️⃣ Final amount
print(f"\nYou are taking home a total of ₹{total_amount}!")